name: CI

# Controls when the workflow will run
on: [ push, pull_request,  workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
     image: debian:bookworm

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          apt-get update
          apt install lsb-release
          lsb_release -a
          
